### ISSUE TITLE
Openshift (Docker) Registry 

### ISSUE THREAD

**Issue by incubus8** [dwmkerr/terraform-aws-openshift#2]
Hi Dave,

it's me Rheza, from Jenius.
Will be good if we have docker registry in this setup. We can specify it easily with S3 as storage in ansible inventory.

**Comment by dwmkerr** [comment]
Hi @incubus8 good idea. Currently the setup has a registry but it is ephemeral, so it'll get wiped on restart. Will see what I can do!

**Comment by dwmkerr** [comment]
Hi @incubus8 was just looking into this, the registry service is definitely running by default as part of this setup:

![image](https://cloud.githubusercontent.com/assets/1926984/22655249/29ff83ac-ecc2-11e6-869a-6168c992cd78.png)

![image](https://cloud.githubusercontent.com/assets/1926984/22655337/6f4e4c9a-ecc2-11e6-9b4e-66e45d24c4f1.png)

Were you having issues with it? Or is it only that you need a persistent storage backend for the registry?

**Comment by ribeaud** [comment]
Hi,
Related to this issue, how can I access the registry from outside?
Currently, I am _pulling_ the images from [AWS ECR](https://aws.amazon.com/ecr/). But, because we already have a **Docker** registry in this installation, I would like to be able to directly _push_ to it. How could I?
Given the defined _docker-registry-default_ route:
<img width="1081" alt="openshift" src="https://user-images.githubusercontent.com/13186156/34158202-c1834c04-e4c4-11e7-9303-4cd3a28217a9.png">
I tried to login, using the same credentials than the ones used for accessing **OpenShift**. But then, I am getting:
`Error response from daemon: Get https://docker-registry-default.xx.xxx.xxx.xxx.xip.io/v2/: x509: certificate signed by unknown authority`
What am I doing wrong?
Many thanks for your work and your support. Kindest regards,
christian

**Comment by ribeaud** [comment]
Hi,
OK, just found out. The _registry-console-default_ provides me the answer:
1. Login to the registry console (https://registry-console-default.xx.xxx.xxx.xxx.xip.io/) using **OpenShift** credentials. This will provide you the credentials for accessing the registry. And, by the way, nicely displays the current state of the registry.
1. Add _docker-registry-default.xx.xxx.xxx.xxx.xip.io_ to the list of unsecure registries to your **Docker** client.
1. Login with `docker login ...`
Et voilà! Cheers,
christian

**Comment by dwmkerr** [comment]
@ribeaud thanks for the info - to make things clearer in the future I've added a lot more documentation on this in the `README.md` file.

**Comment by ribeaud** [comment]
@dwmkerr marvelous! Thanks and cheers, christian.
